# External plugins
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-paginate-v2
  - mini_magick

include: ['_pages']
exclude:
  - "/vendor/"
  - "/.idea/"
  - "*.bat"
  - "Gemfile*"
  - "circle.yml"
  - "LICENSE.md"
  - "README.md"
  - "featured.json"

# Build website in _site during development
destination: "./_site"

future: true

# Site settings
title: 4DCu.be
subtitle: "a blog about programming, gaming, technology, ..."
email: sebastian.proost@gmail.com
name: Sebastian Proost
description: "A blog about Programming (mostly in Python), Machine Learning, Gaming, Technology and more."

# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/icons/apple-icon-76x76.png"
sticker: "/assets/sticker_large.png"

# Build settings
markdown: kramdown
inter_post_navigation: true
highlightjs_theme: "mono-blue"

# Pagination Settings
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
pagination:
  enabled: true
  per_page: 7
  permalink: "/page/:num/"
  sort_reverse: true

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
    - year
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
    year: '/year/:year/'
  cover: "/assets/images/headers/gameboyzero.jpg"

thumbnail:
    resize_dimensions: '430x288^'
    crop_dimensions: '430x288+0+0'

gallery_items:
    resize_dimensions: '430x288^'
    crop_dimensions: '430x288+0+0'

# Disqus comments
disqus_shortname: 4dcube

# Google analytics
# Disable for development
# ga_tracking_id: "UA-47068418-5"

# Buy me a Coffee username
buy_me_a_coffee_username: "4dcube"

# Category descriptions (for archive pages)
descriptions:
  - cat: programming
    desc: "Everything related with code, programming, ..."

  - cat: games
    desc: "All work and no play ..."

  - cat: diy
    desc: "Not everything needs to be digital !"

  - cat: general
    desc: "Things about 4DCu.Be"

# Social icons and sharing options
social:
  - name: Twitter
    icon: twitter
    username: ProostSebastian
    url: https://twitter.com/ProostSebastian
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: 4dcu-be
    url: https://github.com/4dcu-be
    desc: Fork me on GitHub
    share: false

  - name: GitHub
    icon: github
    username: sepro
    url: https://github.com/sepro
    desc: Fork me on GitHub
    share: false

  - name: Facebook
    icon: facebook
    desc: Share on Facebook
    share: true

  - name: LinkedIn
    icon: linkedin
    desc: Share on LinkedIn
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/social_fb.jpg"
    fb_image_width: 1200
    fb_image_height: 630
    fb_image_type: "image/jpg"

    twitter_image: "/assets/social_fb.jpg"

    os_repo: "https://github.com/4dcu-be/4dcu.be"
    os_rcs_type: "git"
    os_src: "git@github.com:4dcu-be/4dcu.be.git"
